### ISSUE TITLE
Don't Working ubuntu 21.04

### ISSUE THREAD

**Issue by pianist2189** [iceland2k14/bsgs#31]
Traceback (most recent call last):
  File "/home/pianist/bsgs-main/v5_secp256k1_bloom_dll/bsgs_hybrid_dll_secp256k1.py", line 115, in <module>
    ice.hash_to_address.argtypes = [ctypes.c_int, ctypes.c_bool, ctypes.c_char_p]  # 012,comp,hash
  File "/usr/lib/python3.9/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/pianist/bsgs-main/v5_secp256k1_bloom_dll/ice_secp256k1.so: undefined symbol: hash_to_address

**Comment by bvazx** [comment]
Windows 10, same here!
